const products = [
  {
    _id: '1',
    name: 'Susu Murni',
    image: '/images/susu-murni-original.jpg',
    description:
      'Kesegaran susu sapi murni 100% tanpa tambahan gula atau pengawet. Creamy, sehat, dan menyegarkan dahaga seketika.',
    brand: 'Klimboys',
    category: 'Milk Series',
    price: 15000,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Susu Cokelat',
    image: '/images/susu-murni-cokelat.jpg',
    description:
      'Perpaduan sempurna antara susu segar dengan cokelat premium Belgia. Rasa manis yang pas dan tekstur yang lembut di mulut.',
    brand: 'Klimboys',
    category: 'Milk Series',
    price: 18000,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Susu Greentea',
    image: '/images/susu-murni-greentea.jpg',
    description:
      'Susu segar dicampur dengan bubuk matcha asli pilihan. Aroma teh hijau yang wangi memberikan ketenangan di setiap tegukan.',
    brand: 'Klimboys',
    category: 'Milk Series',
    price: 20000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Susu Oreo',
    image: '/images/susu-murni-oreo.jpg',
    description:
      'Favorit semua kalangan! Susu creamy dengan campuran remahan biskuit Oreo yang melimpah. Sensasi crunchy dan manis yang bikin nagih.',
    brand: 'Klimboys',
    category: 'Milk Series',
    price: 22000,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Susu Strawberry',
    image: '/images/susu-murni-strawberry.jpg',
    description:
      'Kombinasi susu murni dengan selai stroberi asli yang memiliki bulir buah. Rasa manis asam yang segar, sangat cocok untuk hari yang panas.',
    brand: 'Klimboys',
    category: 'Milk Series',
    price: 18000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Susu Taro',
    image: '/images/susu-murni-taro.jpg',
    description:
      'Rasa unik dari ubi ungu (Taro) yang manis dan legit berpadu dengan susu. Memberikan warna ungu cantik dan rasa yang nostalgic.',
    brand: 'Klimboys',
    category: 'Milk Series',
    price: 18000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Cheese Cream Original',
    image: '/images/cheese-cream-original.jpg',
    description:
      'Minuman signature dengan topping foam keju (cheese cream) yang tebal, gurih, dan asin. Ciptakan kumis keju di setiap tegukanmu!',
    brand: 'Klimboys',
    category: 'Cheese Series',
    price: 25000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Cheese Cream Oreo',
    image: '/images/cheese-cream-oreo.jpg',
    description:
      'Upgrade level ngemil kamu dengan perpaduan cheese cream yang gurih dan taburan Oreo yang manis. Keseimbangan rasa yang sempurna.',
    brand: 'Klimboys',
    category: 'Cheese Series',
    price: 27000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Pasta Creamy Chicken',
    image: '/images/spagetty-creamy-chicken.jpg',
    description:
      'Spaghetti yang dimasak al dente dengan saus krim putih kental, dilengkapi potongan ayam dadu dan taburan parsley serta keju parmesan.',
    brand: 'Klimboys',
    category: 'Main Course',
    price: 35000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Honey Lime Chicken',
    image: '/images/honey-lime-chicken.jpg',
    description:
      'Potongan ayam juicy yang dipanggang dengan glaze madu dan perasan jeruk nipis segar. Disajikan dengan nasi hangat dan salad.',
    brand: 'Klimboys',
    category: 'Main Course',
    price: 32000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
